language: rust

rust:
- nightly
- stable

if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

script:
  - ci/script.sh

cache: cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
